apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    role: locust-worker
  name: locust-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      role: locust-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: locust-worker
    spec:
      containers:
      - image: locustio/locust:2.43.3
        imagePullPolicy: IfNotPresent
        name: locust-worker
        args: ["--worker", "--master-host=locust-master"]
        env:
          - name: LOCUST_HOST
            valueFrom:
              configMapKeyRef:
                name: locust-cm
                key: ATTACKED_HOST
          - name: LOCUST_MODE
            value: WORKER
          - name: LOCUST_LOCUSTFILE
            value: /mnt/locust/locustfile.py
          - name: LOCUST_MASTER
            value: locust-master
        volumeMounts:
          - mountPath: /mnt/locust
            name: locust-scripts
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm